board: MKS-DLC32 V2.1
name: DLC32_X_Min_Test
kinematics: {}
stepping:
  engine: I2S_STATIC
  idle_ms: 0
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17
axes:
  shared_stepper_disable_pin: i2so.0

  x:
    soft_limits: true
    max_travel_mm: 125

    steps_per_mm: 157.75
    max_rate_mm_per_min: 8000
    acceleration_mm_per_sec2: 300

    homing:
      cycle: 1
      positive_direction: false
      seek_mm_per_min: 4000
      feed_mm_per_min: 600
      settle_ms: 150

    motor0:
      limit_neg_pin: gpio.36:low
      hard_limits: false
      pulloff_mm: 1
      stepstick:
        step_pin: i2so.1
        direction_pin: i2so.2:low
        disable_pin: NO_PIN
        ms1_pin: NO_PIN
        ms2_pin: NO_PIN
        ms3_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN

  homing_runs: 1
